### ISSUE TITLE
Merging with vLLM main branch

### ISSUE THREAD

**Issue by zhuohan123** [EmbeddedLLM/vllm-rocm#12]
Hi EmbeddedLLM team,

We are the maintainers of the vLLM project. We just found this project and it's very exciting! Are you interested in contributing the fork to the main branch to add official support to ROCM in vLLM? Feel free to reach out to me at `zhuohan[at]berkeley.edu` and happy to help in any way.

Thanks,
Zhuohan

**Comment by tanpinsiang** [comment]
Absolutely, @zhuohan123. We're thrilled at the opportunity to contribute to the vLLM project and fully committed to integrating ROCm support. Thank you for reaching out and offering your help.

You can monitor our progress and collaboration on this PR: https://github.com/vllm-project/vllm/pull/1749.

**Comment by tanpinsiang** [comment]
The ROCm support has been successfully merged. You can find the changes in the following pull request: https://github.com/vllm-project/vllm/pull/1836.
