### ISSUE TITLE
ImportError: cannot import name 'cuda_utils' from partially initialized module 'vllm'

### ISSUE THREAD

**Issue by wpf19911118** [EmbeddedLLM/vllm-rocm#9]
When I use -tp >1 , the error occurs!
env:
8*MI210
images:embeddedllminfo/vllm-rocm:vllm-v0.2.1.post1

**Comment by tanpinsiang** [comment]
@wpf19911118 can you post your error? We are trying to reproduce it.

**Comment by wpf19911118** [comment]
> @wpf19911118 can you post your error? We are trying to reproduce it.

I made a mistake. When I started the benchmark test, it automatically loaded the vllm related libraries from the source code.
